name: 'Docker Image Tag'
description: 'Outputs a nice Docker image tag for GitHub container registry'

inputs:
  product-name:
    description: 'Your product name'
    required: true
  service-suffix:
    description: 'Specifies suffix with service name'
    required: false
  input-version:
    description: 'Passes given version to tag instead of Git tag'
    required: false

outputs:
  image-tag:
    description: 'Ready-to-use image tag'
    value: ${{ steps.generate-tag.outputs.image-tag }}

runs:
  using: 'composite'
  steps:
    - name: Generate image tag for ghcr.io
      id: generate-tag
      shell: bash
      run: |
        prefix="$( \
          ${{ github.action_path }}/generate-prefix.sh \
            "${{ inputs.product-name }}" \
            "${{ inputs.service-suffix }}" \
            "${{ github.repository }}" \
        )"

        echo "prefix=${prefix}" >> $GITHUB_OUTPUT

        image_tag="$( \
          ${{ github.action_path }}/generate-tag.sh \
            "${prefix}" \
            "${{ inputs.input-version }}" \
            "${{ github.ref_type }}" \
            "${{ github.ref_name }}" \
            "${{ github.sha }}"
        )"

        echo "image-tag=${image_tag}" >> $GITHUB_OUTPUT
    - name: Update GITHUB_PATH
      shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
